name: Build on Tag
on:
  push:
    tags: '*'
    branches: main                                   # Branch to build.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Android kernel build
      uses: malikh0206/android-kernel-actions-modif1@master
      id: build
      env:
        NAME: Custom-Kernel-A32
      with:
        arch: arm64
        compiler: clang/9/binutils
        defconfig: a32_eur_open_defconfig
        image: Image.gz

    - name: Create an Tag
  # You may pin to the exact commit or the version.
  # uses: simpleactions/create-tag@d5c32a2d86b1f96142bbe1ebe8b3b62b0a0587ff
      uses: simpleactions/create-tag@v1.0.0
      with:
    # The GitHub token (if not provided the environment variable GITHUB_TOKEN will be used instead)
        github_token: ${{ secrets.GITHUB_TOKEN }} # optional
    # The commit sha
        sha: ${{ GITHUB_SHA }} # optional
    # The tag name
        tag: ${{ GITHUB_RUN_NUMBER }}
    # The message
        message: New release

    - name: Release build on git                   
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
