name: Build on Tag
on:
  push:
    tags: '*'
    branches: main                                   # Branch to build.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v2

    - name: Android kernel build
      uses: malikh0206/android-kernel-actions-modif1@master
      id: build
      env:
        NAME: Custom-Kernel-A32
      with:
        arch: arm64
        compiler: clang/9/binutils
        defconfig: a32_eur_open_defconfig
        image: Image.gz
    
    - name: Create Tag Release
  # You may pin to the exact commit or the version.
  # uses: beyond5959/create-release-github@fca5fb59dbfa2749e2850463e8c5af9e3ee0e270
  uses: beyond5959/create-release-github@v1
  with:
    # The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag
    tag_name: 1.${{ GITHUB_RUN_NUMBER }}
    # The name of the release. For example, `Release v1.0.1`
    release_name: 
    # Text describing the contents of the tag.
    body: # optional
    # `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`
    draft: # optional
    # `true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`
    prerelease: # optional  

    - name: Release build on git                   
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
